api/urls.py
from django.urls import path
from .views import ImageAPIView, ImagesListAPIView, ImagesListAPIView2, ImageUploadView

#from . import views

urlpatterns = [
    path('', ImageAPIView.as_view(), name='index'),
    path('images_list', ImagesListAPIView.as_view()),
    path('images_list2', ImagesListAPIView2.as_view()),
    path('id/<id>', ImageAPIView.as_view()),
    path('upload/', ImageUploadView.as_view(), name='upload'),
    #path('', views.ImageAPI, name='post_single'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="base/index.html")),
    path('api/', include('api.urls')),
    path('images/', include('images.urls', namespace='images')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from .views import ImagesListView

app_name = 'images'

urlpatterns = [
    path('/images', ImagesListView.as_view(), name='images'),
]

api/models.py
from django.db import models

# Create your models here.

images/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


def user_directory_path(instance, filename):
    return 'images'.format(filename)


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Images(models.Model):

    options = (
        ('active', 'Active'),
        ('deactivated', 'Deactivated'),
    )

    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=250)
    alt = models.TextField(null=True)
    image = models.ImageField(
        upload_to=user_directory_path, default='')
    slug = models.SlugField(max_length=250, unique_for_date='created')
    created = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='author')
    status = models.CharField(max_length=11, choices=options, default='active')

    def media_url(self):
        return self.media_url

api/views.py
import json
from wsgiref.util import FileWrapper
from api.custom_renderers import JPEGRenderer, PNGRenderer
from rest_framework import generics, mixins, permissions, authentication, request
from images.models import Images
from .serializers import ImagesSerializer
from rest_framework.response import Response
from rest_framework import viewsets
from rest_framework import renderers
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework.decorators import renderer_classes, api_view
from rest_framework.renderers import StaticHTMLRenderer
from django.http import HttpResponse
from PIL import Image
from .permissions import Basic, Premium, Enterprise, Admin
from rest_framework.parsers import MultiPartParser, FormParser, FileUploadParser


class ImageAPIView(generics.RetrieveAPIView):

    queryset = Images.objects.filter(id=1)
    renderer_classes = [JPEGRenderer, PNGRenderer]
    authentication_classes = [authentication.SessionAuthentication]
    permission_classes = [permissions.IsAuthenticated]

    def get(self, request, *args, **kwargs):
        renderer_classes = [JPEGRenderer]
        queryset = Images.objects.get(id=self.kwargs['id']).image
        data = queryset
        return Response(data, content_type='image/jpg')

class ImagesListAPIView(generics.ListCreateAPIView):
    queryset = Images.objects.all()
    serializer_class = ImagesSerializer
    renderer_classes = [JPEGRenderer, PNGRenderer]

    def get(self, request, *args, **kwargs):

        queryset = Images.objects.filter(author=request.user.id)
        data = queryset
        return Response(data, content_type='image/jpg')


class ImagesListAPIView2(APIView):
    queryset = Images.objects.all()
    serializer_class = ImagesSerializer
    renderer_classes = [JPEGRenderer, PNGRenderer]

    def get(self, request, *args, **kwargs):

        queryset = Images.objects.filter(author=request.user.id)
        data = queryset
        return Response(data, content_type='image/jpg')


class ImageUploadView(generics.ListCreateAPIView):
    queryset = Images.objects.all()
    serializer_class = ImagesSerializer
    parser_classes = [MultiPartParser, FormParser]

    def post(self, request, *args, **kwargs):
        file = request.data['file']
        author = request.user
        image = Images.objects.create(image=file, author=author)
        return HttpResponse(json.dumps({'message': "Uploaded"}), status=200)

images/views.py
from django.views.generic import ListView
from .models import Images


class ImagesListView(ListView):
    model = Images
    template_name = 'images/show_all.html'

templates/base/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <title>{% block title %} Django Rest API Project {% endblock %}</title>

  <style>
    .small {
      font-size: 0.875rem;
      color: #4b4b4b;
    }
  </style>

</head>

<body>

  {% block content %}
  {% endblock %}

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>
</body>

</html>

templates/base/footer.html
<footer class="font-small bg-dark pt-4">
    <div class="container">
        <ul class="py-2">
        </ul>
    </div>
    <div class="py-3">
    </div>
</footer>

templates/base/index.html
    {% extends "../base/base.html" %}
    {% block title %}
    Django Rest Framework API Project
    {% endblock %}
    {% block content %}
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;600&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&family=Roboto:wght@500&display=swap');

        h1 {
            font-family: 'Work Sans', sans-serif;
            font-weight: 600;
        }

        .txt-robo {
            font-family: 'Roboto', sans-serif;
            font-weight: 500
        }

        p {
            font-family: 'Open Sans', sans-serif;
        }

        h4 {
            font-weight: 300
        }

        .bg-dark {
            background-color: #000000 !important;
        }

        .fs14 {
            font-size: 14px;
        }
    </style>
    <div class="container" style="max-width: 1240px;">
        <div class="row pt-5">
            <div class="col-12 col-md-6">
                <section class="jumbotron bg-white">
                    <div class="container">
                        <h1 class="pt-4"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-image"
                                fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                    d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z" />
                                <path
                                    d="M10.648 7.646a.5.5 0 0 1 .577-.093L15.002 9.5V13h-14v-1l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71z" />
                                <path fill-rule="evenodd" d="M4.502 7a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z" />
                            </svg> Some Image
                        </h1>
                        <p class="h4">Image API Placeholders.</p>
                        <p class="text-muted">
                            Find a list of the images <a href="{% url 'images:images' %}">here</a>
                        </p>
                    </div>
                </section>
            </div>
            <div class=" d-none d-md-none d-md-block col-md-6">
                <section class="jumbotron text-center bg-white px-0">
                    <div class="container">
                        <img class="shadow mb-5 bg-white rounded" src="http://127.0.0.1:8000/api/id/2" width="100%">
                    </div>
                </section>
            </div>
        </div>
    </div>
    <section class="jumbotron text-center">
        <div class="container" style="max-width: 600px;">
            <h1 class="txt-robo h1">Image placeholder</h1>
            <p>URL</p>

            <pre class="bg-white pt-3"><code><a href="http://127.0.0.1:8000/api/id/2">https://127.0.0.1:8000/api/id/2</a></code>
            </pre>

        </div>
    </section>
    <div class="container" style="max-width: 1240px;">
        <div class="row pt-5">
            <div class="col-12 col-md-6">
                <section class="jumbotron bg-white">
                    <div class="container">
                        <h1 class="pt-4 txt-robo h3"> Specific Image
                        </h1>
                        <p>URL</p>
                        </p>
                        <pre class="bg-light text-center pt-3"><code><a href="http://127.0.0.1:8000/api/id/1">https://127.0.0.1:8000/api/id/1</a></code>
            </pre>
                    </div>
                </section>
            </div>
            <div class="d-none d-md-none d-md-block col-md-6">
                <section class="jumbotron text-center bg-white px-0">
                    <div class="container">
                        <img class="shadow mb-5 bg-white rounded" src="http://127.0.0.1:8000/api/id/1" width="100%">
                    </div>
                </section>
            </div>
        </div>
    </div>
    {% include "base/footer.html" %}
    {% endblock %}

templates/images/show_all.html
{% extends "../base/base.html" %}
{% block title %}
Welcome to Blog
{% endblock %}
{% block content %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;600&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&family=Roboto:wght@500&display=swap');

    h1 {
        font-family: 'Work Sans', sans-serif;
        font-weight: 600;
    }

    .txt-robo {
        font-family: 'Roboto', sans-serif;
        font-weight: 500
    }

    p {
        font-family: 'Open Sans', sans-serif;
    }

    h4 {
        font-weight: 300
    }

    .bg-dark {
        background-color: #000000 !important;
    }

    .fs14 {
        font-size: 14px;
    }
</style>
<div class="container" style="max-width: 1240px;">
    <div class="row pt-5">
        <div class="col-12 col-md-6">
            <section class="jumbotron bg-white">
                <div class="container">
                    <h1 class="pt-4"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-card-image"
                            fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd"
                                d="M14.5 3h-13a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z" />
                            <path
                                d="M10.648 7.646a.5.5 0 0 1 .577-.093L15.002 9.5V13h-14v-1l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71z" />
                            <path fill-rule="evenodd" d="M4.502 7a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z" />
                        </svg> Some Image
                    </h1>
                    <p class="h4">Image API Placeholders.</p>
                    <p class="text-muted">
                        Find a list of the images <a href="{% url 'images:images' %}">here</a>
                    </p>
                </div>
            </section>
        </div>
        <div class=" d-none d-md-none d-md-block col-md-6">
            <section class="jumbotron text-center bg-white px-0">
                <div class="container">
                    <img class="shadow mb-5 bg-white rounded" src="http://127.0.0.1:8000/api/id/2" width="100%">
                </div>
            </section>
        </div>
    </div>
</div>
<section class="jumbotron text-center">
    <div class="container" style="max-width: 600px;">
        <h1 class="txt-robo h1">Easy to use placeholders</h1>
        <p>Just find an image and create a URL, not quite implemented width and height yet!</p>

        <pre class="bg-white pt-3"><code><a href="http://127.0.0.1:8000/api/id/2">https://127.0.0.1:8000/api/id/2</a></code>
            </pre>

    </div>
</section>

<div class="container">
    <div class="py-5">
        <div class="row">
            {% for post in object_list %}
            <div class="col-md-4">
                <a class="text-dark" href="{{post.get_absolute_url}}">
                    <div class="card mb-4 shadow mb-5 bg-white rounded">
                        <img class="card-img-top" src="{{post.image.url}}" alt="{{ post.title }}">
                        <div class="card-body d-flex justify-content-between ">
                            <p>{{post.title|truncatechars:50}}</p>
                            <p>#{{post.id}}</p>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% include "base/footer.html" %}
{% endblock %}